defaultSeverity: warning
extends:
  - stylelint-config-standard
  - stylelint-config-recommended
  - stylelint-config-recommended-scss
plugins:
  - stylelint-scss
rules:
  max-line-length: 200
  alpha-value-notation: "number"
  at-rule-empty-line-before:
    - "never"
    - ignore: ["after-comment", "first-nested", "inside-block", "blockless-after-same-name-blockless", "blockless-after-blockless"]
  color-function-notation: null
  value-keyword-case: null
  no-missing-end-of-source-newline: null
  font-family-name-quotes: null
  selector-class-pattern: null
  declaration-empty-line-before: "never"
  no-descending-specificity: null
  declaration-no-important: true
  selector-pseudo-element-colon-notation: "single"

  # Line Spacing
  rule-empty-line-before:
    - always-multi-line
    - ignore:
        - after-comment
        - first-nested
        - inside-block
  # Disallows
  selector-max-id: 2
  comment-no-empty: true
  declaration-block-no-duplicate-properties: true
  block-no-empty:
    - true
    - ignore:
        - comments
  no-extra-semicolons: true
  color-no-invalid-hex: true
  number-no-trailing-zeros: true
  length-zero-no-unit: true
  scss/at-extend-no-missing-placeholder: null
  at-rule-no-unknown: null
  selector-no-qualifying-type:
    - true
    - ignore:
        - attribute
        - class
        - id
  property-no-unknown:
    - true
    - ignoreProperties:
        - 'box-orient'

  # Nesting
  max-nesting-depth:
    - 8
    - ignore: [ 'blockless-at-rules', 'pseudo-classes' ]

  # Style Guide
  indentation: 2
  declaration-block-trailing-semicolon: "always"
  unit-case: "lower"
  color-hex-case: "lower"
  number-leading-zero: "never"
  unit-no-unknown:
    - true
    - ignoreUnits:
        - /^[-+][\d$(]/
  font-family-no-duplicate-names: true
  string-quotes: "single"
  selector-max-compound-selectors: 6

  # Inner Spacing
  function-calc-no-unspaced-operator: true
  declaration-block-semicolon-newline-after: "always"
  block-opening-brace-space-before: "always"
  block-opening-brace-newline-after: "always"
  block-closing-brace-newline-after: "always"
  declaration-bang-space-after: "never"
  declaration-colon-space-after: "always"
