name: Code Style Lint

on: pull_request

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  phpcs:
    name: PHPCS
    runs-on: ubuntu-latest
    steps:

      # https://github.com/actions/checkout (official)
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: composer:v2, cs2pr
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tool versions
        run: |
          php --version
          composer --version

      - name: Install Composer dependencies
        working-directory: ./wp-content/themes/action-test/
        run: composer install --dev --prefer-dist --no-progress --no-suggest --ignore-platform-reqs

      - name: PHPCS check
        working-directory: ./wp-content/themes/action-test/
        continue-on-error: true
        run: |
          echo "::add-matcher::.github/matchers/phpcs-problem-matcher.json"
          ./vendor/bin/phpcs --report=checkstyle -q --standard=phpcs.xml.dist .
          echo "::remove-matcher owner=phpcs"
