name: Code Style Lint

on: pull_request

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  phpcs:
    name: PHPCS
    runs-on: ubuntu-latest
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      # https://github.com/actions/checkout (official)
      - name: Checkout
        uses: actions/checkout@v3

      # Setup PHP with required extensions and tools in GitHub Actions.
      # https://github.com/shivammathur/setup-php (community)
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: composer:v2, cs2pr
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Outputs the PHP version and Composer version while the action is running.
      - name: Tool versions
        run: |
          php --version
          composer --version

      # Using the working-directory keyword, you can specify the working directory of where to run the command.
      # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun
      - name: Install Composer dependencies
        working-directory: ./wp-content/themes/action-test/
        run: composer install --prefer-dist --no-progress --ignore-platform-reqs

      # Problem Matchers documentation
      # https://github.com/actions/toolkit/blob/main/docs/commands.md#problem-matchers
      - name: PHPCS check
        working-directory: ./wp-content/themes/action-test/
        run: |
          echo "::add-matcher::.github/matchers/phpcs-problem-matcher.json"
          ./vendor/bin/phpcs --report=checkstyle -q --standard=phpcs.xml.dist .
          echo "::remove-matcher owner=phpcs"
