name: Code Style Lint

# To automatically trigger a workflow, use "on" to define
# which events can cause the workflow to run.
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on
on: pull_request

# You can use defaults.run to provide default shell and working-directory options
# for all run steps in a workflow.
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defaultsrun
defaults:
  run:
    shell: bash
    working-directory: ./wp-content/themes/action-test/

# Use concurrency to ensure that only a single job or workflow
# using the same concurrency group will run at a time.
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs, which run in parallel by default.
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobs
jobs:

  ### Job to categorize changed files. Other jobs depend on this to know when they should run.
  changed_files:
    name: detect changed files
    runs-on: ubuntu-latest
    outputs:
      # Whether any PHP files have changed.
      php: ${{ steps.filter.outputs.php }}

      # Whether any JavaScript files have changed.
      js: ${{ steps.filter.outputs.js }}

      # Whether any SCSS files have changed.
      scss: ${{ steps.filter.outputs.scss }}

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      # https://github.com/actions/checkout (official)
      - name: Checkout
        uses: actions/checkout@v3

      # Enables conditional execution of workflow steps and jobs,
      # based on the files modified by pull request.
      # https://github.com/dorny/paths-filter
      - name: Detect changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: shell
          filters: |
            php:
              - added|modified:
                - '**.php'
            js:
              - added|modified:
                - '**.js'
            scss:
              - added|modified:
                - '**.scss'

  # Use jobs.<job_id> to give your job a unique identifier.
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_id
  phpcs:

    # Use jobs.<job_id>.name to a name for the job, which is displayed on GitHub.
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idname
    name: PHPCS

    # Use jobs.<job_id>.runs-on to define the type of machine to run the job on.
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest

    needs: changed_files
    if: ${{ needs.changed_files.outputs.php == 'true' }}

    # A job contains a sequence of tasks called "steps".
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idsteps
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      # Setup PHP with required extensions and tools in GitHub Actions.
      # https://github.com/shivammathur/setup-php (community)
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: composer:v2, cs2pr
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Outputs the PHP version and Composer version while the action is running.
      - name: Tool versions
        run: |
          php --version
          composer --version

      # Composer install
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --ignore-platform-reqs

      # Problem Matchers documentation
      # https://github.com/actions/toolkit/blob/main/docs/commands.md#problem-matchers
      - name: PHPCS check
        run: |
          echo "::add-matcher::.github/matchers/phpcs-problem-matcher.json"
          ./vendor/bin/phpcs --report=checkstyle -q --standard=phpcs.xml.dist ${{ needs.changed_files.outputs.php_files }}
          echo "::remove-matcher owner=phpcs"

  eslint:

    name: Eslint
    runs-on: ubuntu-latest

    needs: changed_files
    if: ${{ needs.changed_files.outputs.js == 'true' }}

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: './wp-content/themes/action-test/.nvmrc'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install
        run: npm install --production=false

      - name: Run ESLint
        run: npx eslint ${{ needs.changed_files.outputs.js_files }}

  stylelint:

    name: Stylelint
    runs-on: ubuntu-latest

    needs: changed_files
    if: ${{ needs.changed_files.outputs.scss == 'true' }}

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: './wp-content/themes/action-test/.nvmrc'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install
        run: npm install --production=false

      - name: Run SCSS
        run: npx stylelint ${{ needs.changed_files.outputs.scss_files }}
